DROP DATABASE IF EXISTS JavaEEPOS;
CREATE DATABASE IF NOT EXISTS JavaEEPOS;
SHOW DATABASES;
USE JavaEEPOS;

DROP TABLE IF EXISTS Customer;
CREATE TABLE IF NOT EXISTS Customer
(
    id      VARCHAR(15),
    name    VARCHAR(45) NOT NULL DEFAULT 'Unknown',
    address TEXT,
    salary  DOUBLE               DEFAULT 0.00,
    CONSTRAINT PRIMARY KEY (id)
);
SHOW TABLES;
DESCRIBE Customer;

DROP TABLE IF EXISTS Item;
CREATE TABLE IF NOT EXISTS Item
(
    code      VARCHAR(15),
    name      TEXT,
    unitPrice DOUBLE DEFAULT 0.00,
    qtyOnHand INT    DEFAULT 0,
    CONSTRAINT PRIMARY KEY (code)
);
SHOW TABLES;
DESCRIBE Item;

DROP TABLE IF EXISTS `Order`;
CREATE TABLE IF NOT EXISTS `Order`
(
    orderId   VARCHAR(15),
    orderDate DATE,
    cId       VARCHAR(15),
    cost      DOUBLE,
    CONSTRAINT PRIMARY KEY (orderId),
    CONSTRAINT FOREIGN KEY (cId) REFERENCES Customer (id) ON DELETE CASCADE ON UPDATE CASCADE
);
SHOW TABLES;
DESCRIBE `Order`;


DROP TABLE IF EXISTS `Order Detail`;
CREATE TABLE IF NOT EXISTS `Order Detail`
(
    orderId   VARCHAR(15),
    itemCode  VARCHAR(15),
    itemName  TEXT,
    unitPrice DOUBLE DEFAULT 0.00,
    qty       INT,
    total     DOUBLE,
    CONSTRAINT PRIMARY KEY (itemCode, orderId),
    CONSTRAINT FOREIGN KEY (itemCode) REFERENCES Item (code) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY (orderId) REFERENCES `Order` (orderId) ON DELETE CASCADE ON UPDATE CASCADE
);
SHOW TABLES;
DESCRIBE `Order Detail`;